
[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.14"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.6.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/tokencard/assets"

[[constraint]]
  name = "github.com/tokencard/ethertest"
  version = "0.1.0"

[prune]
  go-tests = true
